[package]
name = "bozzard-player"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true
build = "../../tools/steam_build.rs"

[features]
default = ["steam"]
steam = ["bozzard-demo/steam"]

[dependencies]
serde_json.workspace = true
accesskit = "0.24.1"
accesskit_winit = "0.32.0"
bozzard-audio.workspace = true
bozzard-project = { path = "../../crates/bozzard-project" }
bozzard-assets.workspace = true
bozzard-app.workspace = true
bozzard-demo.workspace = true
bozzard-render.workspace = true
bozzard-render-assets.workspace = true
bozzard-scene.workspace = true
glam.workspace = true
anyhow.workspace = true
pollster.workspace = true
winit.workspace = true

[lints]
workspace = true
