[package]
name = "bozzard-editor-app"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[[bin]]
name = "bozzard-editor"
path = "src/main.rs"

[dependencies]
bozzard-editor = { path = "../../crates/bozzard-editor" }
bozzard-demo.workspace = true
bozzard-scene.workspace = true
bozzard-assets.workspace = true
bozzard-render.workspace = true
anyhow.workspace = true
glam.workspace = true
serde.workspace = true
serde_json.workspace = true
pollster.workspace = true
eframe = { version = "0.36.1", default-features = false, features = ["wgpu", "default_fonts", "x11", "wayland", "persistence"] }

[lints]
workspace = true
