[package]
name = "bozzard-server"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
ctrlc = { version = "3.5", features = ["termination"] }
bozzard-network = { path = "../../crates/bozzard-network" }
bozzard-demo.workspace = true
anyhow.workspace = true

[lints]
workspace = true
