[package]
name = "bozzard-runtime"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true
build = "../../tools/steam_build.rs"

[features]
steam = ["bozzard-network/steam"]

[dependencies]
bozzard-network = { path = "../bozzard-network" }
serde_json.workspace = true
serde.workspace = true
bozzard-diagnostics.workspace = true
bozzard-app.workspace = true
bozzard-scene.workspace = true
anyhow.workspace = true
glam.workspace = true

[lints]
workspace = true
