[package]
name = "bozz-torio"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true
build = "../../tools/steam_build.rs"

[features]
default = ["steam"]
steam = ["dep:steamworks"]

[dependencies]
anyhow.workspace = true
serde.workspace = true
serde_json.workspace = true
image.workspace = true
bozzard-assets.workspace = true
bozzard-ecs.workspace = true
bozzard-render.workspace = true
bozzard-render-assets.workspace = true
bozzard-scene.workspace = true
glam.workspace = true
pollster.workspace = true
winit.workspace = true
steamworks = { version = "0.13.1", optional = true }

[lints]
workspace = true
