[package]
name = "bozz-torio"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true
build = "../../tools/steam_build.rs"

[features]
default = ["steam"]
steam = ["dep:steamworks", "dep:bozzard-network"]

[dependencies]
anyhow.workspace = true
serde.workspace = true
serde_json.workspace = true
image.workspace = true
bozzard-assets.workspace = true
bozzard-app.workspace = true
bozzard-diagnostics.workspace = true
bozzard-ecs.workspace = true
bozzard-render.workspace = true
bozzard-render-assets.workspace = true
bozzard-project = { path = "../../crates/bozzard-project" }
bozzard-scene.workspace = true
glam.workspace = true
pollster.workspace = true
winit.workspace = true
base64 = "0.22.1"
flate2 = "1.1.10"
sha2 = "0.10.9"
steamworks = { version = "0.13.1", optional = true }
bozzard-network = { path = "../../crates/bozzard-network", features = ["steam"], optional = true }

[lints]
workspace = true

[dev-dependencies]
bozzard-demo.workspace = true
