[package]
name = "bozzard-assets"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
bozzard-app.workspace = true
bozzard-compute.workspace = true
bozzard-scene.workspace = true
bozzard-text.workspace = true
anyhow.workspace = true
glam.workspace = true
image.workspace = true
tobj.workspace = true
gltf.workspace = true
base64.workspace = true
serde_json.workspace = true
serde.workspace = true
kira.workspace = true
meshopt = "=0.6.2"
texpresso = "=2.0.2"
ctt-astcenc = "=0.5.0"
sha2 = "=0.10.9"

[lints]
workspace = true
