//! Shared native build setup. Cargo stages the same SDK used by steamworks-sys.
use std::{
    env, fs,
    path::{Path, PathBuf},
};

type BuildResult<T> = Result<T, Box<dyn std::error::Error>>;

fn main() -> BuildResult<()> {
    println!("cargo:rerun-if-env-changed=STEAM_SDK_LOCATION");
    println!("cargo:rerun-if-env-changed=CARGO_HOME");
    if env::var_os("CARGO_FEATURE_STEAM").is_none() {
        return Ok(());
    }
    let os = env::var("CARGO_CFG_TARGET_OS")?;
    let arch = env::var("CARGO_CFG_TARGET_ARCH")?;
    let (folder, library) = match (os.as_str(), arch.as_str()) {
        ("windows", "x86_64") => ("win64", "steam_api64.dll"),
        ("linux", "x86_64") => ("linux64", "libsteam_api.so"),
        ("linux", "aarch64") => ("linuxarm64", "libsteam_api.so"),
        ("macos", "x86_64" | "aarch64") => ("osx", "libsteam_api.dylib"),
        _ => return Err(format!("Unsupported Steam target: {os}/{arch}").into()),
    };
    let explicit = env::var_os("STEAM_SDK_LOCATION").map(PathBuf::from);
    // Cargo supplies an absolute CARGO_HOME to build scripts, including relative user overrides.
    let cargo_home = env::var_os("CARGO_HOME").map(PathBuf::from);
    let source = find_library(explicit.as_deref(), cargo_home.as_deref(), folder, library)?;
    println!("cargo:rerun-if-changed={}", source.display());
    println!("cargo:rustc-env=BOZZARD_STEAM_LIBRARY={library}");
    println!(
        "cargo:rustc-env=BOZZARD_STEAM_LIBRARY_PATH={}",
        source.display()
    );
    let out = PathBuf::from(env::var_os("OUT_DIR").ok_or("missing OUT_DIR")?);
    let profile = out
        .ancestors()
        .nth(3)
        .ok_or("unexpected Cargo output layout")?;
    let bytes = fs::read(&source)?;
    for directory in [profile.to_owned(), profile.join("deps")] {
        fs::create_dir_all(&directory)?;
        let target = directory.join(library);
        // Avoid rewriting a loaded DLL on Windows when another app is running.
        if fs::read(&target).ok().as_deref() != Some(&bytes) {
            fs::write(target, &bytes)?;
        }
    }
    // Executables and exported games load their adjacent redistributable without a launcher.
    match os.as_str() {
        "linux" => println!("cargo:rustc-link-arg=-Wl,-rpath,$ORIGIN"),
        "macos" => println!("cargo:rustc-link-arg=-Wl,-rpath,@loader_path"),
        _ => {}
    }
    Ok(())
}

/// Read only the pinned package already downloaded for the Steam dependency graph.
/// Never run Cargo from here: metadata would resolve unrelated workspace packages, even offline.
pub(crate) fn find_library(
    explicit: Option<&Path>,
    cargo_home: Option<&Path>,
    folder: &str,
    library: &str,
) -> BuildResult<PathBuf> {
    let relative = Path::new("redistributable_bin").join(folder).join(library);
    if let Some(sdk) = explicit {
        return sdk.join(relative).canonicalize().map_err(|error| {
            format!("Cannot read Steam SDK at {}: {error}", sdk.display()).into()
        });
    }
    let version = locked_sys_version()?;
    let cache = cargo_home
        .ok_or("Cargo did not provide CARGO_HOME; set STEAM_SDK_LOCATION to the SDK directory")?
        .join("registry/src");
    let mut candidates = Vec::new();
    if cache.is_dir() {
        for registry in fs::read_dir(&cache)? {
            let source = registry?
                .path()
                .join(format!("steamworks-sys-{version}"))
                .join("lib/steam")
                .join(&relative);
            if source.is_file() {
                candidates.push(source.canonicalize()?);
            }
        }
    }
    candidates.sort();
    candidates.dedup();
    let first = candidates.first().ok_or_else(|| format!(
        "Cannot find the downloaded steamworks-sys {version} SDK in {}. For vendored or path dependencies, set STEAM_SDK_LOCATION to the selected crate's lib/steam directory.", cache.display()
    ))?;
    // Multiple registries can cache the same crate. Never silently choose differing SDK binaries.
    let bytes = fs::read(first)?;
    for candidate in &candidates[1..] {
        if fs::read(candidate)? != bytes {
            return Err("Conflicting cached Steam SDKs; set STEAM_SDK_LOCATION to the SDK used by steamworks-sys".into());
        }
    }
    Ok(first.clone())
}

pub(crate) fn locked_sys_version() -> BuildResult<&'static str> {
    // Cargo.lock is generated by Cargo; package names and semver versions are plain quoted strings.
    let mut versions = include_str!("../Cargo.lock")
        .split("[[package]]")
        .filter(|block| {
            block
                .lines()
                .any(|line| line.trim() == "name = \"steamworks-sys\"")
        })
        .filter_map(|block| {
            block
                .lines()
                .find_map(|line| line.trim().strip_prefix("version = \""))
        })
        .filter_map(|version| version.strip_suffix('"'));
    let version = versions
        .next()
        .ok_or("steamworks-sys is missing from Cargo.lock")?;
    if versions.next().is_some() {
        return Err(
            "Multiple steamworks-sys versions are locked; set STEAM_SDK_LOCATION explicitly".into(),
        );
    }
    Ok(version)
}
