[package]
name = "bozzard-render-assets"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
accesskit = "0.24.1"
bozzard-assets.workspace = true
bozzard-scene.workspace = true
bozzard-render.workspace = true
glam.workspace = true
anyhow.workspace = true

[lints]
workspace = true

[dev-dependencies]
pollster.workspace = true
